In [1]:
print("welcome to Python!")

welcome to Python!


# Python data types, methods for moving data, functions

#### Interested in how to use markdown in jupyter notebook? (support math)

## A. Get familiar with jupyter notebook

### 1.  Try to create a code block under this line.

### 2. Try to move the code block above to below.

### 3. Try to write 1+1 in the code block above, run it (shift+enter or ctl+enter) , then cut it, then paste it below.

### Nice Work!

### Jupyter notebook have autocomplete function. Try to press "tab" at the end of the second line in code block below:

In [2]:
import numpy as np
np.arr

AttributeError: module 'numpy' has no attribute 'arr'

### Jupter notebook holds magic self-carring function: e.g. timing a program use %%time at the beginning

In [3]:
%%time
import time
summ = 0
for i in range(10):
    summ = summ + i
    time.sleep(0.1)

Wall time: 1.01 s


## B. Python import of modules

In [4]:
import numpy 
numpy.sqrt(9)

3.0

In [5]:
sqrt(9)

NameError: name 'sqrt' is not defined

In [6]:
import numpy as np
np.sqrt(9)

3.0

## Python variables and type

### Variables for computation: scalar (int and float), vector (array and matrix) 

In [7]:
#scalar
a = 1
b = 1.0
print(type(a))
print(type(b))

<class 'int'>
<class 'float'>


In [8]:
a+b

2.0

In [9]:
type(a+b)

float

In [10]:
#vector
import numpy as np
'''
Core usage to use np.array():
variable-name = np.array([xxx])
'''
a = np.array([ 1,2,3,4 ]) # vector without dimension

In [11]:
a

array([1, 2, 3, 4])

In [12]:
a.shape

(4,)

In [13]:
b = np.array([ [1,2,3,4] ]) # vector with dimension 1*4
c = np.array([ [1],[2],[3],[4] ]) # vector with dimesion 4*1
### In the braket, each one more braket means each row.

In [14]:
b

array([[1, 2, 3, 4]])

In [15]:
b.shape

(1, 4)

In [16]:
c

array([[1],
       [2],
       [3],
       [4]])

In [17]:
c.shape

(4, 1)

In [18]:
b.T

array([[1],
       [2],
       [3],
       [4]])

In [19]:
d = np.array([ [1,2,3], [4,5,6] ]) # matrix 
d

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
d.shape

(2, 3)

### Variable computation: add, subtract, multiply, dot, divide, inverse

In [21]:
e = d
# add: element-wise
e+d

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [22]:
np.add(e,d)

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [23]:
# subtratc: element-wise
e-d

array([[0, 0, 0],
       [0, 0, 0]])

In [24]:
np.subtract(e,d)

array([[0, 0, 0],
       [0, 0, 0]])

In [25]:
# multiply: element-wise
e*d

array([[ 1,  4,  9],
       [16, 25, 36]])

In [26]:
np.multiply(e,d)

array([[ 1,  4,  9],
       [16, 25, 36]])

In [27]:
# dot: matrix multiplication

$$\begin{array}{l}
{\rm{e}} = \left( {\begin{array}{*{20}{c}}
{\begin{array}{*{20}{c}}
1&2&3
\end{array}}\\
{\begin{array}{*{20}{c}}
4&5&6
\end{array}}
\end{array}} \right) \in {R^{2*3}}\\
d = \left( {\begin{array}{*{20}{c}}
{\begin{array}{*{20}{c}}
1&2&3
\end{array}}\\
{\begin{array}{*{20}{c}}
4&5&6
\end{array}}
\end{array}} \right) \in {R^{2*3}} \Rightarrow {d^T} = \left( {\begin{array}{*{20}{c}}
{\begin{array}{*{20}{c}}
1\\
2\\
3
\end{array}}&{\begin{array}{*{20}{c}}
4\\
5\\
6
\end{array}}
\end{array}} \right) \in {R^{3*2}}\\
e{d^T} = \left( {\begin{array}{*{20}{c}}
{1*1 + 2*2 + 3*3}&{1*4 + 2*5 + 3*6}\\
{4*1 + 5*2 + 6*3}&{4*4 + 5*5 + 6*6}
\end{array}} \right) = ?
\end{array}$$

In [28]:
dt = d.T
dt

array([[1, 4],
       [2, 5],
       [3, 6]])

In [29]:
dt = d.reshape(3,2)
dt

array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
np.dot(e,dt)

array([[22, 28],
       [49, 64]])

In [31]:
# divide: element-wise
e/d

array([[1., 1., 1.],
       [1., 1., 1.]])

In [32]:
np.divide(e,d)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [33]:
# inverse of matrix

#### If given $A \in {R^{n*n}}$, the inverse of $A$, denoted as ${A^{ - 1}} \in {R^{n*n}}$, is the matrix such that ${A^{ - 1}}A = A{A^{ - 1}} = I$.

In [34]:
a = np.array([ [1,2], [3,4] ])
a

array([[1, 2],
       [3, 4]])

In [35]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

### Variables for logic: boolean type

In [36]:
1 = 2

SyntaxError: can't assign to literal (<ipython-input-36-c0ab9e3898ea>, line 1)

In [37]:
1 == 2

False

In [38]:
1 >= 2 

False

In [39]:
1 >= 1

True

In [40]:
1 != 2

True

In [41]:
1 != 1

False

In [42]:
a = True
a

True

In [43]:
True == False

False

In [44]:
True * 5

5

In [45]:
True + 1 

2

In [46]:
True == 1

True

In [47]:
False == 0

True

### Boolean operations

In [48]:
a = True
b = False

In [49]:
a & b

False

In [50]:
a and b

False

In [51]:
a | b

True

In [52]:
a or b

True

In [53]:
x = 3
(x>=1) & (x<=5) # will be used in controling statement

True

### Variables as container: string, list, tuple, dictionary

#### string

In [54]:
a = 'this is string'
b = "this is string"
c = '''this is string'''
a

'this is string'

In [55]:
a == b 

True

In [56]:
b == c

True

In [57]:
c = "
this is string
"

SyntaxError: EOL while scanning string literal (<ipython-input-57-3c250d4eb7a9>, line 1)

In [58]:
c = '''
this is long string'''

In [59]:
c

'\nthis is long string'

In [60]:
d = '\nthis is long string'

In [61]:
c == d

True

In [62]:
e = '''Here "is a 'complex string'"'''

In [63]:
e

'Here "is a \'complex string\'"'

In [64]:
# string operation

In [65]:
'a' + 'b'

'ab'

In [66]:
'a'.upper()

'A'

In [67]:
'this is mine'.upper()

'THIS IS MINE'

In [68]:
'this is mine'.capitalize()

'This is mine'

In [69]:
'a b c'.split(' ')

['a', 'b', 'c']

In [70]:
'this is an example'.replace('is','was')

'thwas was an example'

In [71]:
# string indexing

In [72]:
'this is me'[0] # In python 0 also represent the first, then 1 is the second

't'

In [73]:
'this is me'[1]

'h'

In [74]:
'this is me'[0:3] # 0:3 stands for 'from 0, count 3 element to output, so the last index is 2'.

'thi'

In [75]:
'this is me'[:3] # the first position is missing, the default is 0

'thi'

In [76]:
'this is me'[3:] # the last position is missing, it stands for "from the 4th position to the last"

's is me'

In [77]:
'this is me'[-1] # -1 stands for the last 1 elemenet

'e'

In [78]:
'this is me'[:] # both start and end are missing, represent the entire str.

'this is me'

In [79]:
#e.g.
text = 'this is an example'
text.replace('is','was')

'thwas was an example'

In [80]:
## we dont want to replace the first 'is', so:
text[4:].replace('is','was')
text

'this is an example'

#### List

In [81]:
## List is container created by braket, which accepts inputs as all kind of datatype
a = [1,2,3,4]
type(a)

list

In [82]:
a = [1,2,'this','that',['even another list']]

In [83]:
a

[1, 2, 'this', 'that', ['even another list']]

In [84]:
# list is callable, so you can call each element by index
a[0]

1

In [85]:
a[-1]

['even another list']

In [86]:
# list is changeable, so you can change each element easily.
a[-1] = 1

In [87]:
a

[1, 2, 'this', 'that', 1]

In [88]:
## list operarion

In [89]:
b = [1,2,4,4]
c = a + b
c

[1, 2, 'this', 'that', 1, 1, 2, 4, 4]

In [90]:
[1,2,3] * 2

[1, 2, 3, 1, 2, 3]

In [91]:
c.append(5)

In [92]:
c

[1, 2, 'this', 'that', 1, 1, 2, 4, 4, 5]

In [93]:
c.insert(2,6) # put element "6" into the position with index 2.
c

[1, 2, 6, 'this', 'that', 1, 1, 2, 4, 4, 5]

In [94]:
c.count(4) # how many 4 is in c

2

In [95]:
c.reverse()
c

[5, 4, 4, 2, 1, 1, 'that', 'this', 6, 2, 1]

In [96]:
c.remove(1) # only remove the first 1 from the left to right
c

[5, 4, 4, 2, 1, 'that', 'this', 6, 2, 1]

In [97]:
c.pop(0) # given 0 as the certain index position, remove the element on 0 as the index
c

[4, 4, 2, 1, 'that', 'this', 6, 2, 1]

#### tuple

In [98]:
# tuple is similar with list, while create by parentheses
a = (1,2,5,'this','that',4,3)
# if parentheses is missing, the tuple is default
b = 1,4

In [99]:
a

(1, 2, 5, 'this', 'that', 4, 3)

In [100]:
b

(1, 4)

In [101]:
# tuple v.s. list
# tuple is more stable than list, you can't chang items in it by calling index. e.g.
b[0] = 2

TypeError: 'tuple' object does not support item assignment

In [102]:
# and also we dont have various of functions like .append .insert .remove . pop
# so what can we do if we want to change it enforcely?
# tansfer!

In [103]:
a_after = list(a) # list() is used to transfer a callable objective (string, tuple, or even dictionary) into list
a_after.remove('this')
a = tuple(a_after) # tuple() is used to transfer a callable objective (string, list, or even dictionary) into tuple
a

(1, 2, 5, 'that', 4, 3)

#### Dictionary

In [104]:
# Dictionary can be treated as a special type of list. In list, we have many elements, 
# and their indexes are nature numbers: 0,1,2,... But sometimes, we want a much more complicated index, e.g. string type.
a = {'name':'Bruce','age':23,'job':'student'} 
# dictionary is created by curly bracket, containing pairs of key,colon,value elements, saperated by comma 

In [105]:
## to obtain the value, we use the key as the index:
a['name']

'Bruce'

In [106]:
## or
a.get('name')

'Bruce'

In [107]:
## Sometimes, it there is no key name that we are searching, and also we dont want the program to throw out error, we use
a.get('fack_key','No key exist')

'No key exist'

In [108]:
## the items function return a list a tuple that consists every (key,value) pair
a.items()

dict_items([('name', 'Bruce'), ('age', 23), ('job', 'student')])

In [109]:
## to add a new key:value item in dictionary, we use:
# dictionary_name[key] = value
a['university'] = 'uconn'
a

{'name': 'Bruce', 'age': 23, 'job': 'student', 'university': 'uconn'}

In [110]:
# or also, we can use the .update() function for dictionary to add new element:
a.update({'state':'CT'})
a

{'name': 'Bruce',
 'age': 23,
 'job': 'student',
 'university': 'uconn',
 'state': 'CT'}

In [111]:
# to delete element in dictinary, we use del and call the key:
del a['state']
a

{'name': 'Bruce', 'age': 23, 'job': 'student', 'university': 'uconn'}

### (Important) Data indexing and moving

#### Have you ever used R before? U may remember there is something in R that is similar with excel table, holding column names and even row names. That is the "Dataframe". In Python, we also have dataframe, and is really frequently used.

In [112]:
# To create dataframe:
import pandas as pd
# method 1: create from dictionary with {'column name1':[column values],'column name2':[column values],...}
data = pd.DataFrame({'x':[0,1,2,3,4],'y':[5,6,7,8,9]})
data

x  y
0  0  5
1  1  6
2  2  7
3  3  8
4  4  9

In [113]:
# method 2: create from numpy array with columns name
data_values = np.array([[0,5],[1,6],[2,7],[3,8],[4,9]])
data = pd.DataFrame(data=data_values,columns=['x','y'])
data

x  y
0  0  5
1  1  6
2  2  7
3  3  8
4  4  9

In [114]:
# method 3: loading from cvs, excel, or even txt
data = pd.read_csv('data_file.csv')
data

x  y
0  0  5
1  1  6
2  2  7
3  3  8
4  4  9

In [115]:
data = pd.read_csv('data_file.txt',sep=' ')
data

x  y
0  0  5
1  1  6
2  2  7
3  3  8
4  4  9

In [116]:
## after creating the dataframe you can always change the row name, i.e. the index by:

In [117]:
data.index = ['a','b','c','d','e']

In [118]:
data

x  y
a  0  5
b  1  6
c  2  7
d  3  8
e  4  9

#### How to index the data?

#### 1.By row

In [128]:
# u can use the .loc[] function on data to call by row name
data.loc['a']

x    0
y    5
Name: a, dtype: int64

In [123]:
## multiple rows
data.loc[['a','d']]

x  y
a  0  5
d  3  8

In [124]:
# u can also use the .iloc[] function if you dont know exactly the row name but u know the row number u want to get
data.iloc[0]

x    0
y    5
Name: a, dtype: int64

In [125]:
## multiple rows
data.iloc[[0,3]]

x  y
a  0  5
d  3  8

#### 2.By column

In [129]:
# u can get the column of the data by directly use ['column name'] after the data
data['x']

a    0
b    1
c    2
d    3
e    4
Name: x, dtype: int64

In [130]:
# multiple columns
data[['x','y']]

x  y
a  0  5
b  1  6
c  2  7
d  3  8
e  4  9

In [135]:
#also, silimar with row index, if you dont know the column name, u can also call it by nature index in .iloc[] function
data.iloc[:,0]

a    0
b    1
c    2
d    3
e    4
Name: x, dtype: int64

In [136]:
# multiple columns
data.iloc[:,[0,1]]

x  y
a  0  5
b  1  6
c  2  7
d  3  8
e  4  9

In [137]:
# certainly, the index on row and column could be used together to pinpoint a certain position:
data.iloc[[0,4]]['x']

a    0
e    4
Name: x, dtype: int64

In [138]:
data['x'].iloc[[0,4]]

a    0
e    4
Name: x, dtype: int64

#### How to select from data?

<img src="https://pandas.pydata.org/docs/_images/03_subset_rows.svg">

#### In R we have subset() method to select data from dataframe. What in Python?

In [139]:
data #If we want to select the row of data such that they hold x greater than 0 by smaller than 4.

x  y
a  0  5
b  1  6
c  2  7
d  3  8
e  4  9

In [140]:
data[ (data['x']>0) & (data['x']<4) ]

x  y
b  1  6
c  2  7
d  3  8

In [142]:
# Or if we just want x as the only column?
data.loc[(data['x']>0) & (data['x']<4),'x']

b    1
c    2
d    3
Name: x, dtype: int64

#### The reason?

In [146]:
(data['x']>0) 

a    False
b     True
c     True
d     True
e     True
Name: x, dtype: bool

In [147]:
# It generate a datatype which called "Pandas series", which specify a one-dimension dataframe data.
type((data['x']>0))

pandas.core.series.Series

In [149]:
# This type of data is very popular, e.g.
type(data['x'])

pandas.core.series.Series

In [150]:
type(data['y'])

pandas.core.series.Series

In [151]:
# and data[ xxx ], when xxx is a boolean type pandas series, it tells computer which rows to choose.

#### Dataframe with the numpy array

#### Up to now, pandas dataframe and numpy, the two things we have learned, can both describe the matix, so what is the difference? 

#### Pandas dataframe holds more information and more combining flexibility between two dataframes, as it can hold column name, row name, while it does not support matrix computation.

#### Numpy array holds more convenience on computation, we have .add(), ... , .dot(). But it holds no column name and row name, lacking the interpretation in reality.

#### However, we can easily transfer them from one to another！

In [152]:
# From numpy arrray to dataframe, we have already shown!
data_values = np.array([[0,5],[1,6],[2,7],[3,8],[4,9]])
data = pd.DataFrame(data=data_values,columns=['x','y'])
data

x  y
0  0  5
1  1  6
2  2  7
3  3  8
4  4  9

In [153]:
# From dataframe to numpy array：
data.values

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

#### Data operation in dataframe and numpy array

#### For dataframe

<img src = 'https://pandas.pydata.org/pandas-docs/stable/_images/merging_concat_basic.png'>

In [160]:
# For vertical combination, we use the concat() (represent for concatenate) method with axis = 0
data0 = data.iloc[0:2,:]
data0

x  y
0  0  5
1  1  6

In [161]:
data1 = data.iloc[2:,:]
data1

x  y
2  2  7
3  3  8
4  4  9

In [163]:
pd.concat((data0,data1),axis=0) # or pd.concat([data0,data1],axis=0) both OK

x  y
0  0  5
1  1  6
2  2  7
3  3  8
4  4  9

In [166]:
## use keys options, there will be a flag that where is combined row is from
data_comb = pd.concat((data0,data1),axis=0,keys= ['data0','data1'])
data_comb

x  y
data0 0  0  5
      1  1  6
data1 2  2  7
      3  3  8
      4  4  9

In [168]:
### The result is a complex dataframe with double index, we will not cover that right now.
data_comb.index

MultiIndex([('data0', 0),
            ('data0', 1),
            ('data1', 2),
            ('data1', 3),
            ('data1', 4)],
           )

In [169]:
### However, what if, the two dataframe hold different column name? e.g.
data0 = pd.DataFrame({'x':[0,1],'y':[5,6],'z':[10,11]})
data0

x  y   z
0  0  5  10
1  1  6  11

In [170]:
data1

x  y
2  2  7
3  3  8
4  4  9

In [171]:
## Let's try this:
data_comb = pd.concat((data0,data1),axis=0)
data_comb

C:\Users\jinju\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  


x  y     z
0  0  5  10.0
1  1  6  11.0
2  2  7   NaN
3  3  8   NaN
4  4  9   NaN

In [176]:
data_comb = pd.concat((data0,data1),axis=0,join='inner')
data_comb

x  y
0  0  5
1  1  6
2  2  7
3  3  8
4  4  9

In [177]:
# With dataframes hold totally differen column name, we can use concat method with axis=1 to combine horizontally
data2 = pd.DataFrame({'g':[1,0],'w':[3,1]})
data2

g  w
0  1  3
1  0  1

In [178]:
data0

x  y   z
0  0  5  10
1  1  6  11

In [180]:
pd.concat([data0,data2],axis = 1)

x  y   z  g  w
0  0  5  10  1  3
1  1  6  11  0  1

#### What if two dataframes hold some same columns name, while others are differen? There will be 3 situations:

<img src = 'https://pandas.pydata.org/pandas-docs/stable/_images/merging_concat_axis1.png'>

In [181]:
data0 = pd.DataFrame({'a':[1,2,3,4],'b':[1,2,3,4],'c':[1,2,3,4]})
data0

a  b  c
0  1  1  1
1  2  2  2
2  3  3  3
3  4  4  4

In [195]:
data1 = pd.DataFrame({'b':[3,4,5,6],'d':[3,4,5,6]})
data1.index = [2,3,4,5]
data1

b  d
2  3  3
3  4  4
4  5  5
5  6  6

In [196]:
pd.concat([data0,data1],axis=1)

a    b    c    b    d
0  1.0  1.0  1.0  NaN  NaN
1  2.0  2.0  2.0  NaN  NaN
2  3.0  3.0  3.0  3.0  3.0
3  4.0  4.0  4.0  4.0  4.0
4  NaN  NaN  NaN  5.0  5.0
5  NaN  NaN  NaN  6.0  6.0

<img scr = 'https://pandas.pydata.org/pandas-docs/stable/_images/merging_concat_axis1_inner.png'>

<img src = 'https://pandas.pydata.org/pandas-docs/stable/_images/merging_concat_axis1_inner.png'>

In [197]:
pd.concat([data0,data1],axis=1,join='inner')

a  b  c  b  d
2  3  3  3  3  3
3  4  4  4  4  4

<img src = 'https://pandas.pydata.org/pandas-docs/stable/_images/merging_concat_ignore_index.png'>

In [202]:
pd.concat([data0,data1],ignore_index=True,sort=False)

a  b    c    d
0  1.0  1  1.0  NaN
1  2.0  2  2.0  NaN
2  3.0  3  3.0  NaN
3  4.0  4  4.0  NaN
4  NaN  3  NaN  3.0
5  NaN  4  NaN  4.0
6  NaN  5  NaN  5.0
7  NaN  6  NaN  6.0

#### For numpy array

#### Similar with dataframe, the concatenate function under numpy is commonly used.

In [208]:
array0 = data0.values
array0

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]], dtype=int64)

In [209]:
array1 = data0.values
array1

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]], dtype=int64)

In [211]:
np.concatenate((array0,array1),axis=0)

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]], dtype=int64)

In [212]:
np.concatenate((array0,array1),axis=1)

array([[1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4]], dtype=int64)

#### But it you are going to combine two numpy array with wrong dimension mathcing:

In [217]:
array2 = np.array([ [5,5,5], [6,6,6]  ])
array2

array([[5, 5, 5],
       [6, 6, 6]])

In [218]:
np.concatenate((array0,array2),axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly

#### It will throw you an error. Numpy array holds less flexibility for combining operation.